name: Cypress Tests 
on:
  push:
    branches:
      - 'master'  
jobs:
  build:

    runs-on: 
      labels: runner-base

    strategy:
      matrix:
        browser:
          - chrome  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        run: |
          docker build -t myimg -f Dockerfile .
          docker images

      - name: Build and run Cypress tests
        run: |
          docker build -t my-cypress-image -f Dockerfile --build-arg BROWSER=${{ matrix.browser }} .
          docker run --rm  \
            -v $(pwd)/artifacts/screenshots:/Top99TestAutomation/cypress/screenshots \
            -v $(pwd)/artifacts/videos:/Top99TestAutomation/cypress/videos \
            -v $(pwd)/artifacts/reports:/Top99TestAutomation/cypress/reports my-cypress-image          
        env:
          CI: true
          BROWSER: ${{ matrix.browser }}

      - name: Upload Test Screenshots
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cypress-results-screenshots
          path: ./artifacts/screenshots 

      - name: Upload Test videos 
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
            name: cypress-results-videos
            path: ./artifacts/videos          

      - name: Upload Test result 
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
            name: cypress-results-reports 
            path: ./artifacts/reports
       
